# Generated by Django 5.2.5 on 2025-11-02 14:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FactualExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        max_length=50,
                        null=True,
                        verbose_name="Название упражнения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Упражнение",
                "verbose_name_plural": "Фактические упражнения",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="FitnesHelperExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Имя Упражнения",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание упражнения"),
                ),
                (
                    "exercise_technique",
                    models.TextField(blank=True, verbose_name="Техника упражнения"),
                ),
                (
                    "recommendations_for_men",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        verbose_name="Рекомендации мужчинам",
                    ),
                ),
                (
                    "recommendations_for_women",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        verbose_name="Рекомандации женащинам",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        default=None,
                        null=True,
                        upload_to="exercise_avatar/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "png", "jpeg"]
                            )
                        ],
                        verbose_name="Аватар Упражнения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Упражнение ",
                "verbose_name_plural": "Список упражнения",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="PlannedExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        max_length=50,
                        null=True,
                        verbose_name="Название упражнения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Упражнение",
                "verbose_name_plural": "Планированные упражнения",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="Exercises",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        verbose_name="Имя Упражнения",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_exercises",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Упражнение ",
                "verbose_name_plural": "Список упражнения",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="FactualApproach",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "factual_time",
                    models.PositiveIntegerField(
                        blank=True,
                        db_index=True,
                        default=None,
                        null=True,
                        verbose_name="Фактическое время выполнения упражнения(секунды)",
                    ),
                ),
                (
                    "speed_exercise_equipment",
                    models.FloatField(
                        blank=True,
                        db_index=True,
                        default=None,
                        null=True,
                        verbose_name="Скорость",
                    ),
                ),
                (
                    "weight_exercise_equipment",
                    models.FloatField(
                        blank=True,
                        db_index=True,
                        default=None,
                        null=True,
                        verbose_name="Вес",
                    ),
                ),
                (
                    "count_approach",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        db_index=True,
                        default=None,
                        null=True,
                        verbose_name="Количество",
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factual_exercise",
                        to="django_app.factualexercise",
                        verbose_name="Тренировка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подход ",
                "verbose_name_plural": "Фактические подходы",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="Friends",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True, db_index=True, max_length=10, verbose_name="Статус"
                    ),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sender",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор запроса в друзья",
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipient",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Получатель запроса в друзья",
                    ),
                ),
            ],
            options={
                "verbose_name": "Друзья",
                "verbose_name_plural": "Друзья",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="PlannedApproach",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "planned_time",
                    models.PositiveIntegerField(
                        blank=True,
                        db_index=True,
                        default=None,
                        null=True,
                        verbose_name="Планированное время выполнения упражнения(секунды)",
                    ),
                ),
                (
                    "speed_exercise_equipment",
                    models.FloatField(
                        blank=True,
                        db_index=True,
                        default=None,
                        null=True,
                        verbose_name="Скорость",
                    ),
                ),
                (
                    "weight_exercise_equipment",
                    models.FloatField(
                        blank=True,
                        db_index=True,
                        default=None,
                        null=True,
                        verbose_name="Вес",
                    ),
                ),
                (
                    "count_approach",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        db_index=True,
                        default=None,
                        null=True,
                        verbose_name="Количество",
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planned_approach",
                        to="django_app.plannedexercise",
                        verbose_name="Тренировка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подход ",
                "verbose_name_plural": "Планированные подходы",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="Workout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        null=True,
                        verbose_name="Дата прихода",
                    ),
                ),
                (
                    "finish_time",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        null=True,
                        verbose_name="Дата ухода",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        max_length=20,
                        null=True,
                        verbose_name="Имя тренировки",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        max_length=20,
                        null=True,
                        verbose_name="Тип тренировки",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Активна ли тренировка"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        default="workout_avatar/pexels-pixabay-50597.jpg",
                        upload_to="workout_avatar/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "png", "jpeg"]
                            )
                        ],
                        verbose_name="Аватар тренировки",
                    ),
                ),
                (
                    "is_recommended",
                    models.BooleanField(
                        default=False, verbose_name="Рекомендуемая ли тренировка"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_workout",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тренировка",
                "verbose_name_plural": "Тренировки",
                "ordering": ("-id",),
            },
        ),
        migrations.AddField(
            model_name="plannedexercise",
            name="workout",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="planned_workout",
                to="django_app.workout",
                verbose_name="Тренировка",
            ),
        ),
        migrations.AddField(
            model_name="factualexercise",
            name="workout",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="factual_workout",
                to="django_app.workout",
                verbose_name="Тренировка",
            ),
        ),
        migrations.CreateModel(
            name="WorkoutPurpose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        null=True,
                        verbose_name="Дата начала учета цели",
                    ),
                ),
                (
                    "finish_time",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        null=True,
                        verbose_name="Дата конца учета цели",
                    ),
                ),
                (
                    "purpose",
                    models.PositiveSmallIntegerField(
                        blank=True, db_index=True, verbose_name="Цель(Дни)"
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False, verbose_name="Выполнена ли цель"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_purpose",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Цель ",
                "verbose_name_plural": "Цели",
                "ordering": ("-id",),
            },
        ),
    ]
