# Generated by Django 5.2.5 on 2025-09-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="isActive",
            field=models.BooleanField(
                default=True, verbose_name="Активна ли тренировка"
            ),
        ),
    ]
