# Generated by Django 5.2.5 on 2025-11-02 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fitneshelperexercise",
            options={
                "ordering": ("-id",),
                "verbose_name": "Упражнения от Fitnesshelper",
                "verbose_name_plural": "Список упражнений от Fitnesshelper",
            },
        ),
    ]
