# Generated by Django 5.2.5 on 2025-09-12 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0002_workout_isactive"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workout",
            old_name="isActive",
            new_name="is_active",
        ),
    ]
