# Generated by Django 5.2.5 on 2025-11-02 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0002_alter_fitneshelperexercise_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FitnesHelperExercise",
        ),
    ]
