# Generated by Django 5.2.5 on 2025-09-26 23:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0003_rename_isactive_workout_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workout",
            options={},
        ),
        migrations.AddField(
            model_name="workout",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="workout_avatar/pexels-pixabay-50597.jpg",
                upload_to="workout_avatar/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "png", "jpeg"]
                    )
                ],
                verbose_name="Аватар тренировки",
            ),
        ),
    ]
