# Generated by Django 5.2.5 on 2025-11-02 15:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0003_delete_fitneshelperexercise"),
    ]

    operations = [
        migrations.CreateModel(
            name="FitnesHelperExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Имя Упражнения",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание упражнения"),
                ),
                (
                    "exercise_technique",
                    models.TextField(blank=True, verbose_name="Техника упражнения"),
                ),
                (
                    "recommendations_for_men",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        verbose_name="Рекомендации мужчинам",
                    ),
                ),
                (
                    "recommendations_for_women",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        verbose_name="Рекомандации женащинам",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        default=None,
                        null=True,
                        upload_to="exercise_avatar/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "png", "jpeg"]
                            )
                        ],
                        verbose_name="Аватар Упражнения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Упражнения от Fitnesshelper",
                "verbose_name_plural": "Список упражнений от Fitnesshelper",
                "ordering": ("-id",),
            },
        ),
    ]
