# Generated by Django 5.2.5 on 2025-11-03 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0004_fitneshelperexercise"),
    ]

    operations = [
        migrations.AlterField(
            model_name="factualapproach",
            name="exercise",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="factual_exercise",
                to="django_app.factualexercise",
                verbose_name="Упражнение",
            ),
        ),
        migrations.AlterField(
            model_name="plannedapproach",
            name="exercise",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="planned_approach",
                to="django_app.plannedexercise",
                verbose_name="Упражнение",
            ),
        ),
        migrations.CreateModel(
            name="ExerciseReward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criteria",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Критерий награды",
                    ),
                ),
                (
                    "required_result",
                    models.IntegerField(
                        blank=True, verbose_name="Необходимый результат"
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercise_reward",
                        to="django_app.factualexercise",
                        verbose_name="Упражнение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Награда за упражнение",
                "verbose_name_plural": "Награды за упражнения",
                "ordering": ("-id",),
            },
        ),
    ]
