# Generated by Django 5.2.5 on 2025-09-27 01:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0004_alter_workout_options_workout_avatar"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workout",
            options={
                "ordering": ("-id",),
                "verbose_name": "Тренировка",
                "verbose_name_plural": "Тренировки",
            },
        ),
        migrations.AlterField(
            model_name="workout",
            name="avatar",
            field=models.ImageField(
                default="workout_avatar/pexels-pixabay-50597.jpg",
                upload_to="workout_avatar/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "png", "jpeg"]
                    )
                ],
                verbose_name="Аватар тренировки",
            ),
        ),
    ]
