# Generated by Django 5.2.5 on 2025-11-03 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0005_alter_factualapproach_exercise_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exercises",
            options={
                "ordering": ("-id",),
                "verbose_name": "Упражнение ",
                "verbose_name_plural": "Упражнения пользователя",
            },
        ),
        migrations.AlterModelOptions(
            name="fitneshelperexercise",
            options={
                "ordering": ("-id",),
                "verbose_name": "Упражнение от Fitnesshelper",
                "verbose_name_plural": "Упражнения от Fitnesshelper",
            },
        ),
        migrations.AlterField(
            model_name="exercisereward",
            name="criteria",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                unique=True,
                verbose_name="Критерий награды",
            ),
        ),
        migrations.CreateModel(
            name="UserRewardsLogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "count_of_added_stars",
                    models.IntegerField(
                        blank=True, verbose_name="Количество добавленных звезд"
                    ),
                ),
                (
                    "achievement",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        unique=True,
                        verbose_name="Критерий награды",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_rewards_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог награды за упражнения",
                "verbose_name_plural": "Логи наград за упражнения",
                "ordering": ("-id",),
            },
        ),
    ]
