# Generated by Django 5.2.5 on 2025-11-04 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0006_alter_exercises_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exercisereward",
            options={
                "ordering": ("-id",),
                "verbose_name": "Достижение за упражнение",
                "verbose_name_plural": "Достижения за упражнения",
            },
        ),
        migrations.AlterField(
            model_name="exercisereward",
            name="criteria",
            field=models.CharField(
                blank=True, db_index=True, unique=True, verbose_name="Критерий награды"
            ),
        ),
        migrations.AlterField(
            model_name="exercisereward",
            name="exercise",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercise_reward",
                to="django_app.fitneshelperexercise",
                verbose_name="Упражнение",
            ),
        ),
        migrations.AlterField(
            model_name="userrewardslogs",
            name="achievement",
            field=models.CharField(
                blank=True, db_index=True, unique=True, verbose_name="Критерий награды"
            ),
        ),
        migrations.CreateModel(
            name="UserRewardStatuses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exercise_reward",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercise_user_reward",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Упражнение достижения",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_rewards_statuses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Достижение пользователя",
                "verbose_name_plural": "Достижения пользователя",
                "ordering": ("-id",),
            },
        ),
    ]
