# Generated by Django 5.2.5 on 2025-11-04 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0007_alter_exercisereward_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ExerciseReward",
            new_name="ExerciseRewardStatuses",
        ),
    ]
