# Generated by Django 5.2.5 on 2025-10-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0007_alter_exercises_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workout",
            name="name",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                max_length=20,
                null=True,
                verbose_name="Имя тренировки",
            ),
        ),
    ]
