# Generated by Django 5.2.5 on 2025-11-04 11:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0008_rename_exercisereward_exerciserewardstatuses"),
    ]

    operations = [
        migrations.AddField(
            model_name="exerciserewardstatuses",
            name="avatar",
            field=models.ImageField(
                default=None,
                null=True,
                upload_to="exercise_reward_avatar/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "png", "jpeg"]
                    )
                ],
                verbose_name="Аватар Достижения",
            ),
        ),
    ]
