# Generated by Django 5.2.5 on 2025-11-04 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0009_exerciserewardstatuses_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userrewardstatuses",
            name="exercise_reward",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercise_user_reward",
                to="django_app.exerciserewardstatuses",
                verbose_name="Упражнение достижения",
            ),
        ),
    ]
