# Generated by Django 5.2.5 on 2025-10-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0009_workoutpurpose"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutpurpose",
            name="is_completed",
            field=models.BooleanField(default=False, verbose_name="Выполнена ли цель"),
        ),
    ]
