# Generated by Django 5.2.5 on 2025-11-04 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0010_alter_userrewardstatuses_exercise_reward"),
    ]

    operations = [
        migrations.AddField(
            model_name="userrewardstatuses",
            name="date_reward",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                default=datetime.datetime(
                    2025, 11, 4, 13, 1, 31, 125367, tzinfo=datetime.timezone.utc
                ),
                null=True,
                verbose_name="Дата прихода",
            ),
        ),
    ]
