# Generated by Django 5.2.5 on 2025-10-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0010_workoutpurpose_is_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="is_recommended",
            field=models.BooleanField(
                default=False, verbose_name="Рекомендуемая ли тренировка"
            ),
        ),
    ]
