# Generated by Django 5.2.5 on 2025-11-04 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0011_userrewardstatuses_date_reward"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userrewardstatuses",
            name="date_reward",
        ),
        migrations.AddField(
            model_name="userrewardslogs",
            name="date_reward",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                default=datetime.datetime(
                    2025, 11, 4, 13, 2, 9, 546492, tzinfo=datetime.timezone.utc
                ),
                null=True,
                verbose_name="Дата прихода",
            ),
        ),
    ]
