# Generated by Django 5.2.5 on 2025-10-23 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0012_usersession"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserSession",
        ),
    ]
