# Generated by Django 5.2.5 on 2025-11-04 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0012_remove_userrewardstatuses_date_reward_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userrewardslogs",
            name="achievement",
            field=models.CharField(
                blank=True, db_index=True, verbose_name="Критерий награды"
            ),
        ),
        migrations.AlterField(
            model_name="userrewardslogs",
            name="date_reward",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                default=datetime.datetime(
                    2025, 11, 4, 13, 16, 10, 960222, tzinfo=datetime.timezone.utc
                ),
                null=True,
                verbose_name="Дата прихода",
            ),
        ),
    ]
