# Generated by Django 5.2.5 on 2025-11-05 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0013_alter_userrewardslogs_achievement_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userrewardslogs",
            name="date_reward",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                default=datetime.datetime(
                    2025, 11, 5, 14, 29, 7, 688596, tzinfo=datetime.timezone.utc
                ),
                null=True,
                verbose_name="Дата прихода",
            ),
        ),
    ]
