# Generated by Django 5.2.5 on 2025-11-06 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0016_alter_userrewardslogs_date_reward"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userrewardslogs",
            name="date_reward",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                default=datetime.datetime(
                    2025, 11, 6, 11, 4, 8, 222034, tzinfo=datetime.timezone.utc
                ),
                null=True,
                verbose_name="Дата получения награды",
            ),
        ),
    ]
