# Generated by Django 5.2.5 on 2025-11-07 09:30

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0018_alter_userrewardslogs_date_reward"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="exerciserewardstatuses",
            name="criteria",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=150,
                unique=True,
                verbose_name="Критерий награды",
            ),
        ),
        migrations.AlterField(
            model_name="exercises",
            name="name",
            field=models.CharField(
                blank=True, db_index=True, max_length=150, verbose_name="Имя Упражнения"
            ),
        ),
        migrations.AlterField(
            model_name="factualexercise",
            name="name",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                max_length=150,
                null=True,
                verbose_name="Название упражнения",
            ),
        ),
        migrations.AlterField(
            model_name="fitneshelperexercise",
            name="name",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=150,
                unique=True,
                verbose_name="Имя Упражнения",
            ),
        ),
        migrations.AlterField(
            model_name="fitneshelperexercise",
            name="recommendations_for_men",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=150,
                verbose_name="Рекомендации мужчинам",
            ),
        ),
        migrations.AlterField(
            model_name="fitneshelperexercise",
            name="recommendations_for_women",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=150,
                verbose_name="Рекомандации женащинам",
            ),
        ),
        migrations.AlterField(
            model_name="friends",
            name="status",
            field=models.CharField(blank=True, db_index=True, verbose_name="Статус"),
        ),
        migrations.AlterField(
            model_name="plannedexercise",
            name="name",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                max_length=150,
                null=True,
                verbose_name="Название упражнения",
            ),
        ),
        migrations.AlterField(
            model_name="userrewardslogs",
            name="date_reward",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 7, 9, 30, 40, 72251, tzinfo=datetime.timezone.utc
                ),
                null=True,
                verbose_name="Дата получения награды",
            ),
        ),
        migrations.AlterField(
            model_name="workout",
            name="name",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                max_length=150,
                null=True,
                verbose_name="Имя тренировки",
            ),
        ),
        migrations.AlterField(
            model_name="workout",
            name="type",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                null=True,
                verbose_name="Тип тренировки",
            ),
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        max_length=150,
                        null=True,
                        verbose_name="Имя",
                    ),
                ),
                (
                    "surname",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        max_length=150,
                        null=True,
                        verbose_name="Фамилия",
                    ),
                ),
                (
                    "birth_date",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        null=True,
                        verbose_name="Дата рождения",
                    ),
                ),
                (
                    "weight",
                    models.FloatField(
                        blank=True,
                        db_index=True,
                        default=None,
                        null=True,
                        verbose_name="Вес",
                    ),
                ),
                (
                    "height",
                    models.FloatField(
                        blank=True,
                        db_index=True,
                        default=None,
                        null=True,
                        verbose_name="Рост",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        default="profile_avatar/anonim.png",
                        upload_to="profile_avatar/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "png", "jpeg"]
                            )
                        ],
                        verbose_name="Аватар профиля",
                    ),
                ),
                (
                    "stars",
                    models.IntegerField(
                        blank=True, default=0, verbose_name="Фитнес звезды"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль",
                "verbose_name_plural": "Профили",
                "ordering": ("-id",),
            },
        ),
    ]
