# Generated by Django 5.2.5 on 2025-11-07 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0019_alter_exerciserewardstatuses_criteria_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userrewardslogs",
            name="date_reward",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 7, 10, 28, 48, 918676, tzinfo=datetime.timezone.utc
                ),
                null=True,
                verbose_name="Дата получения награды",
            ),
        ),
    ]
