# Generated by Django 5.2.5 on 2025-11-10 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0021_alter_userrewardslogs_date_reward"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userrewardslogs",
            name="date_reward",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 10, 18, 14, 47, 761375, tzinfo=datetime.timezone.utc
                ),
                null=True,
                verbose_name="Дата получения награды",
            ),
        ),
    ]
