# Generated by Django 5.2.5 on 2025-11-10 21:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0022_alter_userrewardslogs_date_reward"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exerciserewardstatuses",
            name="criteria",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=150,
                verbose_name="Критерий награды",
            ),
        ),
        migrations.AlterField(
            model_name="userrewardslogs",
            name="date_reward",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                null=True,
                verbose_name="Дата получения награды",
            ),
        ),
    ]
