# Generated by Django 5.2.5 on 2025-12-02 13:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0024_alter_userrewardslogs_date_reward"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userrewardslogs",
            name="date_reward",
            field=models.DateTimeField(
                default=django.utils.timezone.localtime,
                null=True,
                verbose_name="Дата получения награды",
            ),
        ),
    ]
