# Generated by Django 5.2.5 on 2025-12-02 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0025_alter_userrewardslogs_date_reward"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workout",
            old_name="is_active",
            new_name="is_completed",
        ),
    ]
