# Generated by Django 5.2.5 on 2025-12-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0026_rename_is_active_workout_is_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="is_activ",
            field=models.BooleanField(
                default=True, verbose_name="Активна ли тренировка"
            ),
        ),
        migrations.AlterField(
            model_name="workout",
            name="is_completed",
            field=models.BooleanField(
                default=True, verbose_name="Завершена ли тренировка"
            ),
        ),
    ]
