# Generated by Django 5.2.5 on 2025-12-02 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0027_workout_is_activ_alter_workout_is_completed"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workout",
            old_name="is_activ",
            new_name="is_active",
        ),
    ]
