# Generated by Django 5.2.5 on 2025-12-02 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0028_rename_is_activ_workout_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workout",
            name="is_completed",
            field=models.BooleanField(
                default=False, verbose_name="Завершена ли тренировка"
            ),
        ),
    ]
