# Generated by Django 5.2.5 on 2025-12-07 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0029_alter_workout_is_completed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workout",
            name="is_active",
            field=models.BooleanField(
                default=False, verbose_name="Активна ли тренировка"
            ),
        ),
    ]
