# Generated by Django 5.2.5 on 2025-12-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0030_alter_workout_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plannedexercise",
            name="name",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                null=True,
                verbose_name="Название упражнения",
            ),
        ),
    ]
