# Generated by Django 5.2.5 on 2025-12-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0031_alter_plannedexercise_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exerciserewardstatuses",
            name="criteria",
            field=models.CharField(
                blank=True, db_index=True, verbose_name="Критерий награды"
            ),
        ),
        migrations.AlterField(
            model_name="exercises",
            name="name",
            field=models.CharField(
                blank=True, db_index=True, verbose_name="Имя Упражнения"
            ),
        ),
        migrations.AlterField(
            model_name="factualexercise",
            name="name",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                null=True,
                verbose_name="Название упражнения",
            ),
        ),
        migrations.AlterField(
            model_name="fitneshelperexercise",
            name="name",
            field=models.CharField(
                blank=True, db_index=True, unique=True, verbose_name="Имя Упражнения"
            ),
        ),
        migrations.AlterField(
            model_name="fitneshelperexercise",
            name="recommendations_for_men",
            field=models.CharField(
                blank=True, db_index=True, verbose_name="Рекомендации мужчинам"
            ),
        ),
        migrations.AlterField(
            model_name="fitneshelperexercise",
            name="recommendations_for_women",
            field=models.CharField(
                blank=True, db_index=True, verbose_name="Рекомандации женащинам"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="name",
            field=models.CharField(
                blank=True, db_index=True, default=None, null=True, verbose_name="Имя"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="surname",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                null=True,
                verbose_name="Фамилия",
            ),
        ),
        migrations.AlterField(
            model_name="workout",
            name="name",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                null=True,
                verbose_name="Имя тренировки",
            ),
        ),
    ]
